### ISSUE TITLE
Are you familiar with linuxserver.io images?

### ISSUE THREAD

**Issue by 99linesofcode** [tiredofit/docker-base#1]
Hi Dave,

Been lurking, going through your repositories ever since I stumbled upon your nixos/home-manager configurations (which are a great reference and have allowed me to get up to speed with Nix in a couple of weeks, thanks a lot for that).

I noticed you have been putting out quite a few docker images and I was wondering if you knew about the images by the [linuxserver.io](https://www.linuxserver.io/) collective. They are built around [s6-overlay](https://github.com/just-containers/s6-overlay) and potentially run multiple processes in a single container (i.e. nginx and php-fpm)  so not really compatible with Kubernetes but other than that they are great.

Thought to return the favor of potentially saving you some time. Take care!

edit: links

**Comment by tiredofit** [comment]
Hi! Thanks for reaching out. I'm familiar with the LSIO group and some of the images that are offered offer, even using a few of their '*arr' images myself. We share some similar goals with getting software packaged out there to the community share similar underlying runtimes. 

I have some strict requirements about image execution in some of the clients I provide services for which truly where the source and reasonings as to why those images were birthed. I do quite a lot of custom work for clients and then after a period of time merge it into the images as part of my working agreement with them, providing it doesn't reveal any confidential/proprietary secrets.

Hopefully they are of use to you and others ;) 
Dave
